// vue-app/src/App.vue
<!--
David A. Clark, Jr.
Student #0004796375
Class WDV339-O
Term C202302
Section	01
Project Portfolio III
-->

<script setup>
  // Library Imports

  import { RouterView } from 'vue-router'

  // Application Imports


</script>

<template>
  <header>
    <p>Header</p>
  </header>

  <RouterView />
</template>

// react-app/src/App.js
/*
David A. Clark, Jr.
Student #0004796375
Class WDV339-O
Term C202302
Section	01
Project Portfolio III
*/

// Component

const App = () => {
  return (
    <div className="flex flex-wrap items-center justify-center vh-100">
      <p>Hi! *waves*</p>
    </div>
  );
}

// Exports

export default App;
